export const SERVICES = [
  { name: 'WhatsApp', code: 'wa' },
  { name: 'Telegram', code: 'tg' },
  { name: 'TikTok/Douyin', code: 'tk' },
  { name: 'Google, Youtube, Gmail', code: 'google' },
  { name: 'Amazon', code: 'amz' },
  { name: 'REDnote / 小红书', code: 'red' },
  { name: 'Instagram+Threads', code: 'ig' },
  { name: 'Facebook', code: 'fb' },
  { name: 'Twitter', code: 'tw' },
  { name: 'Discord', code: 'discord' },
  { name: 'Snapchat', code: 'snapchat' },
  { name: 'Netflix', code: 'nf' },
  { name: 'Paypal', code: 'pp' },
  { name: 'Microsoft', code: 'microsoft' },
  { name: 'Apple', code: 'apple' },
  { name: 'Uber', code: 'ub' },
  { name: 'Binance', code: 'bn' },
  { name: 'Coinbase', code: 'coinbase' },
  { name: 'OpenAI/ChatGPT', code: 'openai' },
  { name: 'Steam', code: 'steam' },
  { name: 'Nike', code: 'nike' },
  { name: 'Tinder', code: 'tinder' },
  { name: 'Bumble', code: 'bumble' },
  { name: 'LinkedIn', code: 'linkedin' },
  { name: 'Yahoo', code: 'yahoo' },
  { name: 'Line', code: 'line' },
  { name: 'KakaoTalk', code: 'kakao' },
  { name: 'Viber', code: 'vb' },
  { name: 'Signal', code: 'signal' },
  { name: 'Shopee', code: 'shopee' },
  { name: 'Lazada', code: 'lazada' },
  { name: 'eBay', code: 'ebay' },
  { name: 'AliExpress', code: 'aliexpress' },
  { name: 'Alibaba', code: 'ali' },
  { name: 'Shein', code: 'shein' },
  { name: 'Temu', code: 'temu' },
  { name: 'Airbnb', code: 'airbnb' },
  { name: 'Bolt', code: 'bolt' },
  { name: 'Grab', code: 'grab' },
  { name: 'Lyft', code: 'lyft' },
  { name: 'Cash App', code: 'cash' },
  { name: 'Venmo', code: 'venmo' },
  { name: 'Wise', code: 'wise' },
  { name: 'Skrill', code: 'skrill' },
  { name: 'OKX', code: 'okx' },
  { name: 'Bybit', code: 'abn' },
  { name: 'MEXC', code: 'bii' },
  { name: 'Bitget', code: 'ahq' },
  { name: 'Roblox', code: 'roblox' },
  { name: 'Grindr', code: 'grindr' },
  { name: 'Hinge', code: 'hinge' },
  { name: 'Badoo', code: 'badoo' },
  { name: 'Vinted', code: 'vinted' },
  { name: 'Depop', code: 'depop' },
  { name: 'Fiverr', code: 'fiverr' },
  { name: 'Walmart', code: 'walmart' },
  { name: 'Disney+', code: 'disneyplus' },
  { name: 'Carousell', code: 'carousell' },
  { name: 'BIP', code: 'bip' },
  { name: 'Dubizzle', code: 'dubizzle' },
  { name: 'Tesco', code: 'tesco' },
  { name: 'Swiggy', code: 'swiggy' },
  { name: 'Flipkart', code: 'flipkart' },
  { name: 'Tradingview', code: 'gc' },
  { name: '1xbet', code: '1x' },
  { name: 'bet365', code: 'ie' },
  { name: 'Bilibili', code: 'bilibili' },
  { name: 'Craigslist', code: 'craigslist' },
  { name: 'Affirm', code: 'af' },
  { name: 'Blizzard / Battle', code: 'bz' },
  { name: 'imo', code: 'imo' },
  { name: 'Match', code: 'match' },
  { name: 'OkCupid', code: 'okcupid' },
  { name: 'Wish', code: 'wish' },
  { name: 'TamTam', code: 'tamtam' },
  { name: 'Etsy', code: 'etsy' },
  { name: 'Claude', code: 'claude' },
  { name: 'DeepSeek', code: 'dseek' },
  { name: 'Skype', code: 'sk' },
  { name: 'OfferUp', code: 'offerup' },
  { name: 'BeReal', code: 'bereal' },
  { name: 'Glovo', code: 'glovo' },
  { name: 'Truecaller', code: 'truecaller' },
  { name: 'Twitch', code: 'twitch' },
  { name: 'Zalo', code: 'zalo' },
  { name: 'Yandex', code: 'yandex' },
  { name: 'Wolt', code: 'wolt' },
  { name: 'Lemfi', code: 'lemfi' },
  { name: 'Dream11', code: 'dream11' },
  { name: 'happn', code: 'happn' },
  { name: 'Poshmark', code: 'psm' },
  { name: 'Ticketmaster', code: 'tmaster' },
  { name: 'foodpanda', code: 'foodpanda' },
  { name: 'VKontakte', code: 'vk' },
  { name: 'Ozon', code: 'ozon' },
  { name: 'Wildberries', code: 'wildberries' },
  { name: 'PaysafeCard', code: 'paysafe' },
  { name: 'Naver', code: 'naver' },
  { name: 'Baidu', code: 'baidu' },
  { name: 'Weibo', code: 'weibo' },
  { name: 'Google Voice', code: 'gv' },
  { name: 'Google Developer', code: 'google_developer' },
  { name: 'Alibaba Cloud', code: 'aliyun' },
  { name: 'Azure', code: 'azure' },
  { name: 'Twilio', code: 'twilio' },
  { name: 'PUBG MOBILE', code: 'pubg' },
  { name: 'Foot Locker', code: 'footlocker' },
]

export function getServiceImage(code) {
  return `https://bee-sms.com/image/${code}.png`
}
